Blog app integration specs
newtonah0/My_Blog1 pull request #8
Opened 2024-01-23 07:51 UTC by ometman

We have completed the 'integration specs' of the project on the branch 'Blog_app_integration_specs':
- It was done through pair programming
- The N+1 problem was solved when fetching all posts and their comments for a user.
--- Before the fix:
![beforen+1](https://github.com/newtonah0/My_Blog1/assets/114116376/fa9376bc-c101-4ef6-8b46-8deb4ebd50e4)
---After the fix:
![after n1](https://github.com/newtonah0/My_Blog1/assets/114116376/9c104320-e3ba-4afb-b5b6-e21b6abab664)

- An Integration Specs was written, using the 'Capybara' gem' for the following:
- -- User Index page
- --User show page
- --Use post index page
- --Post show page

2024-01-23 08:13 UTC, OyePriscilla reviewed
Hi @ometman 👍 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Please @ometman kindly take note that you are supposed to use your repo for review, not your partner's repo. Ensure that your partner contribute meaningfully to your PR as well. Thank you. The guideline is screenshot below 👇 

![Design1](https://github.com/newtonah0/My_Blog1/assets/103386183/1d752bfe-cb2d-49fe-9c10-09406e6f885e)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2024-01-23 10:40 UTC, Ibizugbe requested changes
Hi @newtonah0 👋🏼👋🏼👋🏼👋🏼, 

![require_changes](https://github.com/newtonah0/My_Blog1/assets/64643995/7e2aa958-33cc-4a25-a3e1-b6ee7ed3a458)


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅

- [x] Linters are passing👍🏼.
- [x] gitflow is used👍🏼.
- [x] Test cases are properly written for the user index and show page👍🏼.


## Required Changes ♻️

- [ ] Kindly note that a couple of your tests are failing and as a requirement, all tests should be passing. I suggest you ensure all your tests are passing before you proceed to submit, to avoid any form of blocker👍🏼.
<img width="756" alt="image" src="https://github.com/newtonah0/My_Blog1/assets/64643995/c4ef2b25-98b9-42c7-b108-0294a9b7ebfa">


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-23 10:40 UTC, Ibizugbe commented on spec/features/post_index_spec.rb
> +    end
Nice job so far😉. In fulfillment of the[ requirements](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/intergration_spec_and_n_1_project.md) for this milestone, kindly add a test that asserts that you can see a section for pagination if there are more posts than fit on the view😉.

<img width="653" alt="image" src="https://github.com/newtonah0/My_Blog1/assets/64643995/7cc1b57b-f8bf-4749-9e5d-4ab9c6a06769">

2024-01-24 14:45 UTC, mckent05 approved these changes
Hi @ometman , 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👏 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-24 14:57 UTC, merged